# Data paths needed for the model
TRAIN_CSV = 'AudioForgeryDetection/AudioAnalysis/CSV/train.csv'
TEST_CSV = 'AudioForgeryDetection/AudioAnalysis/CSV/test.csv'

exp_1_path = 'PicklesAndFinalModel/mel_preprocess_data_3_chans_history_torch_baseline_convnext_femto_224_custom_exp_0_mel_cv_sin_resize_BASELINE.pkl'
exp_2_path = 'PicklesAndFinalModel/mel_preprocess_data_3_chans_history_torch_baseline_convnext_femto_224_custom_exp_1_mel_cv_sin_resize.pkl'
exp_3_path = 'PicklesAndFinalModel/mel_preprocess_data_3_chans_history_torch_baseline_convnext_femto_224_custom_exp_2_mel_cv_aug_sin_resize.pkl'
exp_4_path = 'PicklesAndFinalModel/mel_preprocess_data_3_chans_history_torch_baseline_convnext_femto_224_custom_exp_3_mel_cv_con_resize.pkl'
exp_5_path = 'PicklesAndFinalModel/mfcc_preprocess_data_3_chans_history_torch_baseline_convnext_femto_224_custom_exp_7_mel_cv_con_resize_mfcc.pkl'